In [3]:
import plotly
import plotly.plotly as py
from plotly.grid_objs import Grid, Column
from plotly import figure_factory as FF 

import pandas as pd
import time
dataset = pd.read_csv('/Users/jun/Desktop/503 project2/cancer_us.csv')
dataset

,YEAR,POPULATION,Mortality_COUNT,Mortality_AGE_ADJUSTED_RATE,Incidence_COUNT,Incidence_AGE_ADJUSTED_RATE
0,1999,279040168,549829,200.498064,1290283,481.0
1,2000,282162411,553080,198.584611,1316928,483.3
2,2001,284968955,553760,196.094126,1357552,484.5
3,2002,287625193,557264,194.196234,1373684,481.8
4,2003,290107933,556890,190.672647,1385384,472.7
5,2004,292805298,553880,186.554751,1406219,471.7
6,2005,295312662,559303,185.031083,1432655,471.8
7,2006,298379912,559880,181.671095,1467268,474.4
8,2007,301231207,562867,178.937767,1510717,478.3
9,2008,304093966,565460,175.940811,1529526,474.1
10,2009,306771529,567614,173.060066,1546769,469.7
11,2010,309348193,574738,171.386325,1540552,458.3
12,2011,311663358,576685,168.356522,1570396,457.8
13,2012,313998379,582607,166.033166,1559679,444.9
14,2013,316204908,584872,162.922393,1580148,441.4
15,2014,318563456,591686,160.946285,1597271,436.8
16,2015,320896618,595919,158.404571,1610533,431.4

In [4]:
import plotly.plotly as py
import plotly.graph_objs as go

trace1 = go.Scatter(
    x = dataset['YEAR'], 
    y = dataset['Mortality_COUNT'], 
    name = "Mortality Count", 
    text = dataset['Mortality_COUNT'], 
    yaxis = "y", 
)

trace2 = go.Scatter(
    x = dataset['YEAR'], 
    y = dataset['Incidence_COUNT'], 
    name = "Incidence_Count", 
    text = dataset['Incidence_COUNT'],
    yaxis = "y2", 
)

trace3 = go.Scatter(
    x = dataset['YEAR'], 
    y = dataset['Mortality_AGE_ADJUSTED_RATE'], 
    name = "Mortality_Rate", 
    text = dataset['Mortality_AGE_ADJUSTED_RATE'],
    yaxis = "y3",
)

trace4 = go.Scatter(
    x = dataset['YEAR'], 
    y = dataset['Incidence_AGE_ADJUSTED_RATE'], 
    name = "Incidence_Rate", 
    text = dataset['Incidence_AGE_ADJUSTED_RATE'],
    yaxis = "y4",
)


data = [trace1, trace2, trace3, trace4]

In [5]:
layout = { 
    
  "xaxis": {
    "autorange": True, 
    "range": ["1999", "2015"], 
    "rangeslider": {
      "autorange": True, 
      "range": ["1999", "2015"]
    }, 
    "type": "date"
  }, 
    
  "yaxis": {
    "anchor": "x", 
    "autorange": True, 
    "domain": [0, 0.25], 
    "linecolor": "#673ab7", 
    "mirror": True, 
    "range": [540000, 600000], 
    "showline": True, 
    "side": "right", 
    "tickfont": {"color": "#673ab7"}, 
    "tickmode": "auto", 
    "ticks": "", 
    #"title": "Mor#",
    "titlefont": {"color": "#673ab7"}, 
    "type": "linear", 
    "zeroline": False
  }, 
    
  "yaxis2": {
    "anchor": "x", 
    "autorange": True, 
    "domain": [0.25, 0.5], 
    "linecolor": "#E91E63", 
    "mirror": True, 
    "range": [1310000, 1620000], 
    "showline": True, 
    "side": "right", 
    "tickfont": {"color": "#E91E63"}, 
    "tickmode": "auto", 
    "ticks": "", 
    #"title": "Inci#", 
    "titlefont": {"color": "#E91E63"}, 
    "type": "linear", 
    "zeroline": False
  }, 
    
  "yaxis3": {
    "anchor": "x", 
    "autorange": True, 
    "domain": [0.5, 0.75], 
    "linecolor": "#795548", 
    "mirror": True, 
    "range": [155, 205], 
    "showline": True, 
    "side": "right", 
    "tickfont": {"color": "#795548"}, 
    "tickmode": "auto", 
    "ticks": "", 
    #"title": "Mor_AAR", 
    "titlefont": {"color": "#795548"}, 
    "type": "linear", 
    "zeroline": False
  }, 
    
  "yaxis4": {
    "anchor": "x", 
    "autorange": True, 
    "domain": [0.75, 1], 
    "linecolor": "#607d8b", 
    "mirror": True, 
    "range": [430, 485], 
    "showline": True, 
    "side": "right", 
    "tickfont": {"color": "#607d8b"}, 
    "tickmode": "auto", 
    "ticks": "", 
    #"title": "Inci_AAR", 
    "titlefont": {"color": "#607d8b"}, 
    "type": "linear", 
    "zeroline": False
  }
}
fig = go.Figure(data=data, layout=layout)
py.iplot(fig)